### ISSUE TITLE
[Bug] No files uploaded to server

### ISSUE THREAD

**Issue by MeVsGOD** [getfian/fian#1]
Not working installation step completed but no files on server uploaded

**Comment by fakerybakery** [comment]
Would you mind explaining further? Do you see anything in your JavaScript console?

**Comment by MeVsGOD** [comment]
Uploaded to web server auto completed 5 steps but nothing Uploaded to web server except that index.php

**Comment by fakerybakery** [comment]
I will look into this. Thank you for reporting this issue!

**Comment by fakerybakery** [comment]
Hello, I have tested the process again and it seems to work. What version of PHP are you using?

**Comment by MeVsGOD** [comment]
Php 7.4

**Comment by fakerybakery** [comment]
Apologies, FIAN only works on PHP 8.1. Please try updating your version and try again. Sorry, I forgot to mention this in the readme. I will add it.
